<?php
$DATA= '0|Is for you?|yes|1|no; it is a gift|2,
1|Do you desperately need it?|yes|3|no; but it is an awesome deal|4,
2|for whom?|friend|12|family|13,
3|Have you searched thrift stores or any website?|yes|8||,
4|How do you know it is an awesome deal?|the price tag literally reads awesome deal|11|I have spent three months comparison shopping|7,
5|Is for you?|yes|1|no; it is a gift|2,
6|Is for you?|yes|1|no; it is a gift|2,
7|Ok  we are backing away slowly|Continue|26||,
8|Yes but there is no way Nike Air Yeez|Continue|9||,
9|Wait.. I thought you said you desperately needed this?						|Yes|10||,
10|Well.. On a second thought		Don't buy it.!||||,
11|Dude…																		|Continue|25||,
12|Would your friend appreciate dinner a movie or a concert?					|yes	|14	|no	|15,
13|Did your family member specifically request this item?						|yes	|16	|no	|22,
14|Go do that; then	Don't buy it. it!												||||,
15|Are you sure they´re your friend?											|Continue|25||,
16|In a whiny or demanding voice that sounds more like a threat tha a requets?	|yes|17|no|20,
17|Who said it?																	|My child|18|My mom|19,
18|seriously;Invest in a parenting book instead									||||,
19|seriously; Invest in therapy instead											||||,
20|No; it was more like a sweet letter or well reasoned argument				|Continue|21||,
21|Well; now you have to so you don´t look a Grinch								|Continue|26||,
22|Does your sister really want these Simpsons-themed riding boots?				|Continue|24||,
23|Ummm…																		|Continue|25||,
24|This is why God created gift card..											|Continue|25||,
25|Don't buy it.																||||,
26|Yes; you can buy it!!..														||||,';?>